[tool.poetry]
name = "manage-fastapi"
version = "0.1.5"
description = "Managing FastAPI projects made easy."
authors = ["ycd <yagizcanilbey1903@gmail.com>"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/ycd/manage-fastapi"
homepage = "https://github.com/ycd/manage-fastapi"

classifiers = [
    "Topic :: Software Development :: Build Tools",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
]
exclude = ["manage_fastapi/tests"]



[tool.poetry.dependencies]
python = "^3.6"
typer = "^0.3.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"


[tool.poetry.scripts]
manage-fastapi = 'manage_fastapi.main:app'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
